### ISSUE TITLE
Unused parameter theta in SIR$dPointObs function

### ISSUE THREAD

**Issue by caijun** [sbfnk/fitR#1]
I am learning the online materials of MFIIDD 2016. The function body of `SIR$dPointObs` is as follows

```
> SIR$dPointObs
function(data.point, model.point, theta, log = FALSE){

    ## the prevalence is observed through a Poisson process
    return(dpois(x = data.point[["obs"]],
                 lambda = model.point[["I"]],
                 log = log))
}
<bytecode: 0x119b6c0a8>
```

You see the parameter `theta` is not used in the function body. The same issue has occurred for function `SIR$rPointObs`.

```
> SIR$rPointObs
function(model.point, theta){

    ## the prevalence is observed through a Poisson process
    obs.point <- rpois(n = 1, lambda = model.point[["I"]])

    return(c(obs = obs.point))
}
<bytecode: 0x1031d6c30>
```

**Comment by sbfnk** [comment]
They're not used in these particular instances, but in principle theta could be used by the point observation functions. Because of this, the functions `dTrajObs` and `rTrajObs` expect `dPointObs` and `rPointObs` to accept a parameter `theta`.
