### ISSUE TITLE
Failing to install fitR package on R

### ISSUE THREAD

**Issue by diliuliu** [sbfnk/fitR#3]
Dear Sebastian,

When I used your code to install the fitR package, it failed and R gave the error that "Error: Does not appear to be an R package (no DESCRIPTION)".

**Comment by sbfnk** [comment]
Please provide the exact command that failed and all output

**Comment by diliuliu** [comment]
Dear Sebastian,

Thank you for your prompt reply.

The exact command that failed is as following:

install_github("sbfnk/fitR") (after I have successfully installed package devtools and library it)

All output is as follows:

Downloading GitHub repo sbfnk/fitR@master
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: running command 'tar.exe -zxf "C:\Users\Di\AppData\Local\Temp\RtmpaSvLKX\filee0b416545ff3.tar.gz" -C "C:/Users/Di/AppData/Local/Temp/RtmpaSvLKX/remotese0b4438a4497"' had status 1 
2: In utils::untar(tarfile, ...) :
  ��tar.exe -zxf "C:\Users\Di\AppData\Local\Temp\RtmpaSvLKX\filee0b416545ff3.tar.gz" -C "C:/Users/Di/AppData/Local/Temp/RtmpaSvLKX/remotese0b4438a4497"�� returned error code 1
3: running command 'tar.exe -ztf "C:\Users\Di\AppData\Local\Temp\RtmpaSvLKX\filee0b416545ff3.tar.gz"' had status 1 

Thank you and best

**Comment by sbfnk** [comment]
This seems to be a known problem with a non-standard tar. Can you try the solution suggested here? https://github.com/r-lib/devtools/issues/1939#issuecomment-445229644

**Comment by diliuliu** [comment]
Problem solved. Thank you very much for your patient reply!
