### ISSUE TITLE
Unable to install fitR

### ISSUE THREAD

**Issue by sjijon** [sbfnk/fitR#6]
When trying to install `fitR` using `devtools`, the following error appears:

```
ERROR: lazy loading failed for package ‘fitR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/fitR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/fitR’
Error: Failed to install 'fitR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/p5/px9_jt496vsdqh5_6csw83980000gn/T//RtmpDkOpJs/file60644b37ffda/fitR_0.1.tar.gz’ had non-zero exit status
```

Running on:
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6 (and also on macOS Catalina 10.15.7)

We tried other ways to install the package, without success:
- We tried to uninstall and reinstall R and RStudio
- We tried older versions of R (3.3.3 and 3.3.6)
- We tried to copy the files directly on the R library (/Library/Frameworks/R.framework/Resource/library), 
- We tried to install the package as a binary (`install.packages("fitR", type = "binary")`)

Could you please give us a hand solving this problem ?

Thanks in advance.

**Comment by sbfnk** [comment]
Was there any more information, e.g. a warning/error given before the installation failed?

**Comment by sjijon** [comment]
Thanks for the quick reply! Here's all the information displayed, while executing the recommended way to install the package:

Using  `remotes::install_github('sbfnk/fitR')` yields:

> Skipping install of 'fitR' from a github remote, the SHA1 (5c0065dd) has not changed since last install.
>   Use `force = TRUE` to force installation

Then, using `remotes::install_github('sbfnk/fitR', force=TRUE)`, we get:

> Downloading GitHub repo sbfnk/fitR@HEAD
> ✓  checking for file ‘/private/var/folders/p5/px9_jt496vsdqh5_6csw83980000gn/T/RtmpDfPCTw/remotes778d69f13c79/sbfnk-fitR-5c0065d/DESCRIPTION’ ...
> ─  preparing ‘fitR’:
> ✓  checking DESCRIPTION meta-information ...
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘fitR_0.1.tar.gz’
>    
> * installing *source* package ‘fitR’ ...
> ** using staged installation
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** byte-compile and prepare package for lazy loading
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
>   Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so
>   Reason: image not found
> Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
> Execution halted
> ERROR: lazy loading failed for package ‘fitR’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/fitR’
> * restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/fitR’
> Error: Failed to install 'fitR' from GitHub:
>   (converted from warning) installation of package ‘/var/folders/p5/px9_jt496vsdqh5_6csw83980000gn/T//RtmpDfPCTw/file778d5cb96245/fitR_0.1.tar.gz’ had non-zero exit status

**Comment by sbfnk** [comment]
Can you try `install.packages("gmm")` and then try installing `fitR` again?

**Comment by sjijon** [comment]
There is still the error loading the `gmm` package after installing it.

**Comment by sbfnk** [comment]
Have you restarted R after re-installing `gmm`?

**Comment by sjijon** [comment]
Yes, with no success.

**Comment by sbfnk** [comment]
Does `library("gmm")` work?

**Comment by sjijon** [comment]
No, I get the error:

> Loading required package: sandwich
> Error: package or namespace load failed for ‘gmm’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
>   Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so
>   Reason: image not found

>

**Comment by sbfnk** [comment]
Sorry, not sure what's going on there but the problem seems to be with the `gmm` library. Normally re-installing and restarting R works in this case.

**Comment by sjijon** [comment]
I see. I will try to solve the problem with `gmm`. Thanks for your help!

**Comment by sjijon** [comment]
The installation problem was indeed related to the `gmm` package, required by `fitR`.

The problem was solved installing `gfortran`, which is available at CRAN [https://cran.r-project.org/bin/macosx/tools/](https://cran.r-project.org/bin/macosx/tools/). Then, restarting R after the installation. 

Loading `gmm` no longer gives an error, nor the installation of `fitR`.
